import { mkdir, readFile, writeFile, readdir, copyFile } from "node:fs/promises";
import { join } from "node:path";

const root = process.cwd();
const canonicalDir = join(root, ".agents", "plugins", "plannic", "skills");
const deployedDir = join(root, ".agents", "skills");

console.log("Syncing skills from canonical source:", canonicalDir);

const entries = await readdir(canonicalDir, { withFileTypes: true });
const skillNames = entries.filter((e) => e.isDirectory()).map((e) => e.name).sort();

const sources: Record<string, string> = {};

for (const name of skillNames) {
  const srcFile = join(canonicalDir, name, "SKILL.md");
  const content = await readFile(srcFile, "utf8");
  sources[name] = content;

  // Deploy to .agents/skills/<name>/SKILL.md
  const destDir = join(deployedDir, name);
  await mkdir(destDir, { recursive: true });
  await copyFile(srcFile, join(destDir, "SKILL.md"));
  console.log(`✔ Synced ${name} -> .agents/skills/${name}/SKILL.md`);
}

// Read Claude command
const claudeFile = join(root, ".claude", "commands", "plannic.md");
const claude = await readFile(claudeFile, "utf8");

// Generate apps/cli/src/generated/agent-assets.ts
const generatedFile = join(root, "apps", "cli", "src", "generated", "agent-assets.ts");
await mkdir(join(root, "apps", "cli", "src", "generated"), { recursive: true });
await writeFile(
  generatedFile,
  `// Auto-generated by scripts/sync-skills.ts — DO NOT EDIT MANUALLY\nexport const agentSkills = ${JSON.stringify(sources, null, 2)} as const;\nexport const claudeCommand = ${JSON.stringify(claude)};\n`
);
console.log(`✔ Updated generated assets -> apps/cli/src/generated/agent-assets.ts`);
console.log(`\n\x1b[32m✔ Successfully synced ${skillNames.length} canonical skills and updated generated assets.\x1b[0m`);
